const GET_CITY_PENDING = "GET_CITY_PENDING";
const GET_CITY_SUCCESS = "GET_CITY_SUCCESS";
const GET_CITY_FAILED = "GET_CITY_FAILED";
const SELECT_CITY = "SELECT_CITY";
const CLEAR_DATA = "CLEAR_DATA";

export default {
  GET_CITY_FAILED,
  GET_CITY_SUCCESS,
  GET_CITY_PENDING,
  SELECT_CITY,
  CLEAR_DATA,
};
